apiHostname = "localhost"
apiPort = 8404
apiKey = "change-me"
srtInUri = "srt://:5000?mode=listener"
# inPipeline = """
#   audiotestsrc is-live=true name=audioinput
#   videotestsrc is-live=true name=videoinput
# """
outUri = "srt://:5001?mode=listener"
# outPipeline = """
#   videoqueue. ! fakesink
#   audioqueue. ! fakesink
# """
# outScript = "echo hello world"
delaySeconds = 15
width = 1920
height = 1080
x264Bitrate = 4500
x264Preset = "slow"
pixelizeScale = 20
overlayImg = "example.overlay.png"
start = true